// แคตตาล็อกไอคอนสำหรับการ์ดเป้าหมายโฟกัส (การเงิน)
// ใช้ Lucide (ฟรี, minimal, สไตล์เดียวกับทั้งแอป) — เก็บชื่อไอคอนเป็น text ใน finance_budgets.icon
// ค้นหาได้ทั้งไทย/อังกฤษผ่าน kw
import {
  Zap, Lightbulb, Plug, BatteryCharging, Flame, Snowflake, Sun, Moon, Umbrella, CloudRain,
  Droplet, Droplets, Home, Building, Building2, Warehouse, Factory, Store, KeyRound, Lock,
  Wifi, Globe, Phone, Monitor, Cpu, HardDrive, Printer, Camera,
  Car, Bike, Bus, TrainFront, Ship, Plane, Truck, Fuel, Navigation, MapPin,
  Wallet, WalletCards, Banknote, Coins, CreditCard, PiggyBank, Receipt, Calculator, Percent,
  BadgeDollarSign, CircleDollarSign, Landmark, Scale, Handshake, TrendingUp, TrendingDown,
  LineChart, BarChart3, PieChart,
  Users, User, Briefcase, GraduationCap, Stethoscope, Pill, Syringe, HeartPulse, Dumbbell,
  Megaphone, PenTool, Palette, Paintbrush, SprayCan, Scissors, Hammer, Wrench,
  Package, Boxes, Box, Archive, ShoppingCart, ShoppingBag, Tag, Tags, Gift,
  Utensils, Coffee, Shirt, Watch, Glasses, Footprints,
  Music, Film, Gamepad2, BookOpen, Newspaper,
  Shield, ShieldCheck, Award, Crown, Gem, Star, Bell, Calendar, Clock, FileText, Recycle, Trees, Leaf,
} from 'lucide-react';

export const BUDGET_ICONS = [
  // สาธารณูปโภค
  { name: 'zap', Icon: Zap, kw: 'ไฟ ไฟฟ้า ค่าไฟ electric power energy' },
  { name: 'lightbulb', Icon: Lightbulb, kw: 'หลอดไฟ ไอเดีย light idea' },
  { name: 'plug', Icon: Plug, kw: 'ปลั๊ก ไฟฟ้า plug' },
  { name: 'battery-charging', Icon: BatteryCharging, kw: 'แบตเตอรี่ ชาร์จ battery' },
  { name: 'droplets', Icon: Droplets, kw: 'น้ำ ค่าน้ำ ประปา water' },
  { name: 'droplet', Icon: Droplet, kw: 'น้ำ หยดน้ำ water' },
  { name: 'flame', Icon: Flame, kw: 'แก๊ส ไฟ gas fire' },
  { name: 'snowflake', Icon: Snowflake, kw: 'แอร์ เย็น air ac' },
  { name: 'wifi', Icon: Wifi, kw: 'เน็ต อินเทอร์เน็ต internet wifi' },
  { name: 'globe', Icon: Globe, kw: 'เว็บ โดเมน อินเทอร์เน็ต web domain hosting' },
  { name: 'phone', Icon: Phone, kw: 'โทรศัพท์ มือถือ phone' },
  // ที่อยู่/สถานที่
  { name: 'home', Icon: Home, kw: 'บ้าน หนี้บ้าน ที่พัก home house' },
  { name: 'building', Icon: Building, kw: 'ตึก อาคาร building' },
  { name: 'building-2', Icon: Building2, kw: 'ออฟฟิศ สำนักงาน office' },
  { name: 'store', Icon: Store, kw: 'ร้าน ค่าเช่า หน้าร้าน shop rent store' },
  { name: 'warehouse', Icon: Warehouse, kw: 'โกดัง คลัง warehouse' },
  { name: 'factory', Icon: Factory, kw: 'โรงงาน factory' },
  { name: 'key-round', Icon: KeyRound, kw: 'กุญแจ เช่า key rent' },
  { name: 'lock', Icon: Lock, kw: 'ล็อค ความปลอดภัย lock security' },
  // ยานพาหนะ/ขนส่ง
  { name: 'car', Icon: Car, kw: 'รถ หนี้รถ รถยนต์ car' },
  { name: 'bike', Icon: Bike, kw: 'จักรยาน มอเตอร์ไซค์ bike' },
  { name: 'truck', Icon: Truck, kw: 'ขนส่ง ส่งของ รถบรรทุก shipping delivery' },
  { name: 'bus', Icon: Bus, kw: 'รถบัส เดินทาง bus' },
  { name: 'train-front', Icon: TrainFront, kw: 'รถไฟ train' },
  { name: 'ship', Icon: Ship, kw: 'เรือ นำเข้า ship import' },
  { name: 'plane', Icon: Plane, kw: 'เครื่องบิน เดินทาง plane travel' },
  { name: 'fuel', Icon: Fuel, kw: 'น้ำมัน เชื้อเพลิง fuel gas' },
  { name: 'navigation', Icon: Navigation, kw: 'เดินทาง นำทาง navigation' },
  { name: 'map-pin', Icon: MapPin, kw: 'สถานที่ พิกัด location' },
  // เงิน/หนี้/ธนาคาร
  { name: 'wallet', Icon: Wallet, kw: 'กระเป๋าเงิน เงินเดือน ค่าแรง wallet salary' },
  { name: 'wallet-cards', Icon: WalletCards, kw: 'กระเป๋า บัตร wallet cards' },
  { name: 'banknote', Icon: Banknote, kw: 'ธนบัตร เงินสด cash' },
  { name: 'coins', Icon: Coins, kw: 'เหรียญ เงิน coins' },
  { name: 'credit-card', Icon: CreditCard, kw: 'บัตรเครดิต หนี้บัตร credit card' },
  { name: 'piggy-bank', Icon: PiggyBank, kw: 'ออม เงินออม savings' },
  { name: 'receipt', Icon: Receipt, kw: 'บิล ใบเสร็จ receipt bill' },
  { name: 'calculator', Icon: Calculator, kw: 'บัญชี คำนวณ ภาษี accounting tax' },
  { name: 'percent', Icon: Percent, kw: 'ดอกเบี้ย เปอร์เซ็นต์ interest' },
  { name: 'badge-dollar-sign', Icon: BadgeDollarSign, kw: 'เงิน ราคา dollar' },
  { name: 'circle-dollar-sign', Icon: CircleDollarSign, kw: 'เงิน dollar' },
  { name: 'landmark', Icon: Landmark, kw: 'ธนาคาร หนี้ กู้ bank loan' },
  { name: 'scale', Icon: Scale, kw: 'กฎหมาย ทนาย บัญชี legal' },
  { name: 'handshake', Icon: Handshake, kw: 'หนี้ลูกค้า คู่ค้า ตกลง deal partner debt' },
  { name: 'trending-up', Icon: TrendingUp, kw: 'กำไร เพิ่ม ลงทุน invest profit' },
  { name: 'trending-down', Icon: TrendingDown, kw: 'ขาดทุน ลด loss' },
  { name: 'line-chart', Icon: LineChart, kw: 'กราฟ สถิติ chart' },
  { name: 'bar-chart-3', Icon: BarChart3, kw: 'กราฟ รายงาน chart report' },
  { name: 'pie-chart', Icon: PieChart, kw: 'สัดส่วน กราฟ pie' },
  // คน/ทีม/สุขภาพ
  { name: 'users', Icon: Users, kw: 'ทีม พนักงาน เงินเดือน ค่าแรง team staff' },
  { name: 'user', Icon: User, kw: 'คน ส่วนตัว person' },
  { name: 'briefcase', Icon: Briefcase, kw: 'งาน ธุรกิจ business' },
  { name: 'graduation-cap', Icon: GraduationCap, kw: 'เรียน คอร์ส การศึกษา education' },
  { name: 'stethoscope', Icon: Stethoscope, kw: 'หมอ สุขภาพ doctor health' },
  { name: 'pill', Icon: Pill, kw: 'ยา medicine' },
  { name: 'syringe', Icon: Syringe, kw: 'ฉีด วัคซีน vaccine' },
  { name: 'heart-pulse', Icon: HeartPulse, kw: 'สุขภาพ ประกัน health insurance' },
  { name: 'dumbbell', Icon: Dumbbell, kw: 'ฟิตเนส ออกกำลัง gym fitness' },
  // การตลาด/งานสร้างสรรค์/ช่าง
  { name: 'megaphone', Icon: Megaphone, kw: 'การตลาด โฆษณา ยิงแอด marketing ads' },
  { name: 'pen-tool', Icon: PenTool, kw: 'ออกแบบ ดีไซน์ design' },
  { name: 'palette', Icon: Palette, kw: 'สี ศิลปะ ออกแบบ art color' },
  { name: 'paintbrush', Icon: Paintbrush, kw: 'ทาสี พ่นสี paint' },
  { name: 'spray-can', Icon: SprayCan, kw: 'พ่นสี สเปรย์ spray' },
  { name: 'scissors', Icon: Scissors, kw: 'ตัด scissors' },
  { name: 'hammer', Icon: Hammer, kw: 'ช่าง ซ่อม เครื่องมือ tools' },
  { name: 'wrench', Icon: Wrench, kw: 'ซ่อม ประแจ อะไหล่ repair' },
  // ของ/สต๊อก/ซื้อขาย
  { name: 'package', Icon: Package, kw: 'พัสดุ กล่อง ส่งของ package' },
  { name: 'boxes', Icon: Boxes, kw: 'สต๊อก กล่อง stock' },
  { name: 'box', Icon: Box, kw: 'กล่อง box' },
  { name: 'archive', Icon: Archive, kw: 'เก็บ archive' },
  { name: 'shopping-cart', Icon: ShoppingCart, kw: 'ซื้อของ วัตถุดิบ shopping' },
  { name: 'shopping-bag', Icon: ShoppingBag, kw: 'ช้อปปิ้ง ซื้อ shopping' },
  { name: 'tag', Icon: Tag, kw: 'ป้ายราคา tag' },
  { name: 'tags', Icon: Tags, kw: 'ป้าย หมวด tags' },
  { name: 'gift', Icon: Gift, kw: 'ของขวัญ ของแถม gift' },
  // กิน/ใช้/ไลฟ์สไตล์
  { name: 'utensils', Icon: Utensils, kw: 'อาหาร กิน ข้าว food' },
  { name: 'coffee', Icon: Coffee, kw: 'กาแฟ เครื่องดื่ม coffee' },
  { name: 'shirt', Icon: Shirt, kw: 'เสื้อผ้า ยูนิฟอร์ม clothes' },
  { name: 'watch', Icon: Watch, kw: 'นาฬิกา watch' },
  { name: 'glasses', Icon: Glasses, kw: 'แว่น glasses' },
  { name: 'footprints', Icon: Footprints, kw: 'รองเท้า เดิน shoes' },
  { name: 'music', Icon: Music, kw: 'เพลง ดนตรี music' },
  { name: 'film', Icon: Film, kw: 'หนัง วิดีโอ streaming' },
  { name: 'gamepad-2', Icon: Gamepad2, kw: 'เกม game' },
  { name: 'book-open', Icon: BookOpen, kw: 'หนังสือ เรียน book' },
  { name: 'newspaper', Icon: Newspaper, kw: 'ข่าว สมาชิก subscription news' },
  // อุปกรณ์/ไอที
  { name: 'monitor', Icon: Monitor, kw: 'คอม จอ อุปกรณ์ computer' },
  { name: 'cpu', Icon: Cpu, kw: 'ชิป ไอที it hardware' },
  { name: 'hard-drive', Icon: HardDrive, kw: 'เก็บข้อมูล เซิร์ฟเวอร์ server' },
  { name: 'printer', Icon: Printer, kw: 'ปริ้น พิมพ์ printer' },
  { name: 'camera', Icon: Camera, kw: 'กล้อง ถ่ายรูป camera' },
  // อื่นๆ
  { name: 'shield', Icon: Shield, kw: 'ประกัน ป้องกัน insurance' },
  { name: 'shield-check', Icon: ShieldCheck, kw: 'ประกัน ปลอดภัย insurance' },
  { name: 'award', Icon: Award, kw: 'รางวัล award' },
  { name: 'crown', Icon: Crown, kw: 'พรีเมียม premium' },
  { name: 'gem', Icon: Gem, kw: 'เพชร ของมีค่า gem' },
  { name: 'star', Icon: Star, kw: 'ดาว star' },
  { name: 'bell', Icon: Bell, kw: 'แจ้งเตือน bell' },
  { name: 'calendar', Icon: Calendar, kw: 'รายเดือน ปฏิทิน calendar' },
  { name: 'clock', Icon: Clock, kw: 'เวลา ล่วงเวลา ot time' },
  { name: 'file-text', Icon: FileText, kw: 'เอกสาร ค่าธรรมเนียม document fee' },
  { name: 'recycle', Icon: Recycle, kw: 'รีไซเคิล ขยะ recycle' },
  { name: 'trees', Icon: Trees, kw: 'ต้นไม้ สวน trees' },
  { name: 'leaf', Icon: Leaf, kw: 'ใบไม้ ธรรมชาติ eco' },
];

// หา component จากชื่อที่เก็บใน DB — ไม่เจอคืน null (การ์ดเก่าที่ยังไม่เลือกไอคอน)
export const budgetIcon = (name) => BUDGET_ICONS.find(i => i.name === name)?.Icon || null;
